# Generated by Django 6.0.3 on 2026-03-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paddy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasedetection',
            name='image',
            field=models.ImageField(max_length=255, upload_to='paddy_images/'),
        ),
    ]
