# Generated by Django 6.0.3 on 2026-03-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paddy_app', '0002_alter_diseasedetection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasedetection',
            name='humidity',
            field=models.FloatField(blank=True, help_text='Humidity percentage', null=True),
        ),
        migrations.AddField(
            model_name='diseasedetection',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='diseasedetection',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Temperature in Celsius', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
